# Generated by Django 5.0.1 on 2024-01-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='procedureApplications',
            new_name='procedures',
        ),
    ]
