# Generated by Django 5.0.1 on 2024-01-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedureapplication',
            old_name='appointmentId',
            new_name='appointment',
        ),
        migrations.RenameField(
            model_name='procedureapplication',
            old_name='doctorId',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='procedureapplication',
            old_name='procedureId',
            new_name='procedure',
        ),
    ]
