# Generated by Django 5.0.1 on 2024-01-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_doctor_email_alter_doctor_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='allergies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='medications',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='surgeries',
            field=models.TextField(null=True),
        ),
    ]
