# Generated by Django 5.0.1 on 2024-01-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0009_alter_appointment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='Dashboard.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedures',
            field=models.ManyToManyField(blank=True, to='Dashboard.procedure'),
        ),
    ]
